config/routes.rb
Rails.application.routes.draw do
  get '/debug/select_actor', to:'debug_pages#select_actor'

  root 'ticket_shops#select_place'
  get '/select_date', to: 'ticket_shops#select_date'
  get '/select_time', to: 'ticket_shops#select_time'

  get '/select_ticket', to: 'ticket_shops#select_ticket'
  get '/buy_ticket', to: 'ticket_shops#buy_ticket'
  get '/thanks', to: 'ticket_shops#thanks'

  get '/staff/signin', to: 'staff_pages#signin'
  get '/staff', to: 'staff_pages#index'
  get '/staff/qrcode_reader', to: 'staff_pages#qrcode_reader'
  get '/staff/buy_detail/:url', to: 'staff_pages#buy_detail'

  get '/eventer/signin', to: 'eventer_pages#signin'
  get '/eventer', to: 'eventer_pages#index'
  get '/eventer/add_event_place', to: 'eventer_pages#add_event_place'
  get '/eventer/add_event_name', to: 'eventer_pages#add_event_name'
  get '/eventer/add_event_time', to: 'eventer_pages#add_event_time'
  get '/eventer/add_ticket', to: 'eventer_pages#add_ticket'
  get '/eventer/add_staff', to: 'eventer_pages#add_staff'
  get '/eventer/day_sales', to: 'eventer_pages#day_sales'
  get '/eventer/day_sales_detail', to: 'eventer_pages#day_sales_detail'
  get '/eventer/ticket_sales_detail', to: 'eventer_pages#ticket_sales_detail'

  resources :users
  get '/signup', to: 'users#signup'
  get '/signin', to: 'users#signin'
  get '/mypage', to: 'users#mypage'
  get '/order_history', to:'users#order_history'
  get '/order_detail', to:'users#order_detail'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event_name.rb
class EventName < ApplicationRecord
  has_many :event_times
end

app/models/event_place.rb
class EventPlace < ApplicationRecord
  has_many :event_times
end

app/models/event_time.rb
class EventTime < ApplicationRecord
  has_many :tickets

  belongs_to :event_name
  belongs_to :event_place
end

app/models/eventer.rb
class Eventer < ApplicationRecord
end

app/models/sale.rb
class Sale < ApplicationRecord
  has_many :sale_tickets, dependent: :destroy
  has_many :tickets, through: :sale_tickets

  belongs_to :user
  belongs_to :staff, optional: true
end

app/models/sale_ticket.rb
class SaleTicket < ApplicationRecord
  belongs_to :sale
  belongs_to :ticket
end

app/models/staff.rb
class Staff < ApplicationRecord
  has_many :sales
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_many :sale_tickets
  has_many :sales, through: :sale_tickets
  belongs_to :event_time
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sales, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/debug_pages_controller.rb
class DebugPagesController < ApplicationController
  def select_actor
    @users = User.all
    @staffs = Staff.all
    @sales = Sale.all
    @eventers = Eventer.all
    @event_places = EventPlace.all
    @event_names = EventName.all
    @event_times = EventTime.all
    @tickets = Ticket.all
    @sale_tickets = SaleTicket.all
  end
end

app/controllers/eventer_pages_controller.rb
class EventerPagesController < ApplicationController
  def signin
  end

  def index
  end

  def add_event_place
  end

  def add_event_name
  end

  def add_event_time
  end

  def add_ticket
  end

  def add_staff
  end

  def day_sales
  end

  def day_sales_detail
  end

  def ticket_sales_detail
  end
end

app/controllers/staff_pages_controller.rb
class StaffPagesController < ApplicationController
  def signin
  end

  def index
  end

  def qrcode_reader
  end

  def buy_detail
    @sale = Sale.find_by(url: params[:url])
  end
end

app/controllers/ticket_shops_controller.rb
class TicketShopsController < ApplicationController
  def select_place
    @event_places = EventPlace.all
  end

  def select_date
    event_times = EventTime.select(:entry_time)
                            .group(:entry_time)
                            .order(entry_time: :asc)

    @event_dates = []
    event_times.each do |event_time|
      @event_dates << event_time.entry_time.to_date
    end
    @event_dates.uniq!
  end

  def select_time
    event_times = EventTime.where("event_place_id = ?", 1)
                          .order(event_name_id: :asc)

    @event_names = []
    ary = []
    temp = nil

    event_times.each do |event_time|
      if event_time.event_name.id != temp && !temp.nil?
        @event_names << ary.dup
        ary.clear
      end
      
      ary << event_time

      temp = event_time.event_name.id
    end
    @event_names << ary.dup
  end

  def select_ticket
    @event = EventTime.first

    @tickets = @event.tickets
  end

  def buy_ticket
    @event = EventTime.first

    @tickets = @event.tickets
  end

  def thanks
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def signup
  end

  def signin
  end

  def mypage
  end

  def order_history
    user = User.first

    @sales = user.sales
  end

  def order_detail
    user = User.first

    @sale = user.sales.first

    @total_price = 0

    qrcode = RQRCode::QRCode.new(@sale.url)
    @svg = qrcode.as_svg(
      color: "000",
      shape_rendering: "crispEdges",
      module_size: 6,
      standalone: true,
      use_path: true
    ).html_safe
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :tel, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/debug_pages_helper.rb
module DebugPagesHelper
end

app/helpers/eventer_pages_helper.rb
module EventerPagesHelper
end

app/helpers/staff_pages_helper.rb
module StaffPagesHelper
end

app/helpers/ticket_shops_helper.rb
module TicketShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/debug_pages/select_actor.html.erb
<h1>デバッグ画面</h1>

<%= link_to 'ユーザ画面', root_path, class: 'btn btn-primary' %>
<%= link_to '主催者管理画面', eventer_signin_path, class: 'btn btn-primary' %>
<%= link_to '受付スタッフ画面', staff_signin_path, class: 'btn btn-primary' %>

<details>
  <summary><%= @users.class %></summary>

  <% @users.reverse.each do |user|%>
    <p><%= pp user.to_json %></p>
  <% end %>
</details>

<details>
  <summary><%= @staffs.class %></summary>

  <% @staffs.reverse.each do |staff|%>
    <p><%= pp staff.to_json %></p>
  <% end %>
</details>

<details>
  <summary><%= @sales.class %></summary>

  <% @sales.reverse.each do |sale|%>
    <p><%= pp sale.to_json %></p>
  <% end %>
</details>

<details>
  <summary><%= @eventers.class %></summary>

  <% @eventers.reverse.each do |eventer|%>
    <p><%= pp eventer.to_json %></p>
  <% end %>
</details>

<details>
  <summary><%= @event_places.class %></summary>

  <% @event_places.reverse.each do |event_place|%>
    <p><%= pp event_place.to_json %></p>
  <% end %>
</details>

<details>
  <summary><%= @event_names.class %></summary>

  <% @event_names.reverse.each do |event_name|%>
    <p><%= pp event_name.to_json %></p>
  <% end %>
</details>

<details>
  <summary><%= @event_times.class %></summary>

  <% @event_times.reverse.each do |event_time|%>
    <p><%= pp event_time.to_json %></p>
  <% end %>
</details>

<details>
  <summary><%= @tickets.class %></summary>

  <% @tickets.reverse.each do |ticket|%>
    <p><%= pp ticket.to_json %></p>
  <% end %>
</details>

<details>
  <summary><%= @sale_tickets.class %></summary>

  <% @sale_tickets.reverse.each do |sale_ticket|%>
    <p><%= pp sale_ticket.to_json %></p>
  <% end %>
</details>

app/views/eventer_pages/add_event_name.html.erb
<h1>EventerPages#add_event_name</h1>
<p>Find me in app/views/eventer_pages/add_event_name.html.erb</p>

app/views/eventer_pages/add_event_time.html.erb
<h1>EventerPages#add_event_time</h1>
<p>Find me in app/views/eventer_pages/add_event_time.html.erb</p>

app/views/eventer_pages/add_staff.html.erb
<h1>EventerPages#add_staff</h1>
<p>Find me in app/views/eventer_pages/add_staff.html.erb</p>

app/views/eventer_pages/add_ticket.html.erb
<h1>EventerPages#add_ticket</h1>
<p>Find me in app/views/eventer_pages/add_ticket.html.erb</p>

app/views/eventer_pages/day_sales.html.erb
<h1>EventerPages#day_sales</h1>
<p>Find me in app/views/eventer_pages/day_sales.html.erb</p>

app/views/eventer_pages/day_sales_detail.html.erb
<h1>EventerPages#day_sales_detail</h1>
<p>Find me in app/views/eventer_pages/day_sales_detail.html.erb</p>

app/views/eventer_pages/index.html.erb
<h1>主催者管理画面</h1>

<%= link_to 'イベント入力', eventer_add_event_name_path, class: 'btn btn-primary' %>
<%= link_to '開催地', eventer_add_event_place_path, class: 'btn btn-primary' %>
<%= link_to '開催時間', eventer_add_event_time_path, class: 'btn btn-primary' %>
<%= link_to 'チケット入力', eventer_add_ticket_path, class: 'btn btn-primary' %>
<%= link_to '受付スタッフ入力', eventer_add_staff_path, class: 'btn btn-primary' %>
<%= link_to '売上確認', eventer_add_event_name_path, class: 'btn btn-primary' %>
<%= link_to 'ログアウト', "#", class: 'btn btn-primary' %>

app/views/eventer_pages/signin.html.erb
<h1>主催者管理画面</h1>

<h2>サインイン</h2>

<input type="text" name="title" size="20" maxlength="28" />
<input type="text" name="title" size="20" maxlength="28" />

<%= link_to 'サインイン', eventer_path, class: 'btn btn-primary' %>

app/views/eventer_pages/ticket_sales_detail.html.erb
<h1>EventerPages#ticket_sales_detail</h1>
<p>Find me in app/views/eventer_pages/ticket_sales_detail.html.erb</p>

app/views/staff_pages/buy_detail.html.erb
<h1>受付スタッフ</h1>

<h2>イベント場所</h2>
<% event_time = @sale.tickets.first.event_time %>
<p><%= event_time.event_place.name %></p>

<h2>日時</h2>
<p><%= event_time.entry_time.to_date %></p>

<h2>イベント</h2>
<p><%= event_time.event_name.name %></p>

<h2>時間</h2>
<img src="https://placehold.jp/150x150.png" class="img-fluid" alt="モックアップ">
<% str_time = [event_time.entry_time.strftime("%R"),
            "~",
            event_time.exit_time.strftime("%R")].join %>
<p><%= str_time %></p>

<h2>購入枚数</h2>
<% @sale.tickets.each do |ticket| %>
  <% sale_ticket = SaleTicket.find_by(sale_id: @sale.id, ticket_id: ticket.id) %>
  <p><%= "#{ticket.name} #{ticket.price}円 #{sale_ticket.count}枚" %></p>
  <p><%= "備考: #{ticket.detail}"%></p>
<% end %>

<p>ステータス：<%= @sale.staff_id.nil? ? "未入場" : "入場済み" %></p>

<%= link_to '入場ボタン', staff_qrcode_reader_path, class: 'btn btn-primary' %>

app/views/staff_pages/index.html.erb
<h1>受付スタッフ</h1>

<%= link_to 'QRコード読み取り', staff_qrcode_reader_path, class: 'btn btn-primary' %>
<%= link_to '履歴', staff_buy_detail_path, class: 'btn btn-primary' %>
<%= link_to 'ログアウト', '#', class: 'btn btn-primary' %>

app/views/staff_pages/qrcode_reader.html.erb
<h1>受付スタッフ</h1>

<h2>QRコード読み取り</h2>

<div id="loading">ブラウザのカメラの使用を許可してください。</div>
<canvas id="canvas" hidden></canvas>

<div id="output">
  <div id="outputMessage">No QR code detected.</div>
  <div hidden=""><b>Data:</b> <span id="outputData"></span></div>
  <a id="url" href="#" class="btn btn-primary">チケット確認</a>
</div>

<script src="https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.min.js"></script>
<script>
  const video = document.createElement("video");
  const canvasElement = document.getElementById("canvas");
  const canvas = canvasElement.getContext("2d");
  const loading = document.getElementById("loading");
  const output = document.getElementById("output");
  const outputMessage = document.getElementById("outputMessage");
  const outputData = document.getElementById("outputData");
  const url = document.getElementById("url")

  navigator.mediaDevices
    .getUserMedia({ video: { facingMode: "environment" } })
    .then((stream) => {
      video.srcObject = stream;
      video.setAttribute("playsinline", true);
      video.play();
      requestAnimationFrame(tick);
    });

  function tick() {
    loading.innerText = "ロード中...";

    if (video.readyState === video.HAVE_ENOUGH_DATA) {
      loading.hidden = true;
      canvasElement.hidden = false;
      canvasElement.height = video.videoHeight;
      canvasElement.width = video.videoWidth;
      canvas.drawImage(
        video,
        0,
        0,
        canvasElement.width,
        canvasElement.height
      );

      var imageData = canvas.getImageData(
        0,
        0,
        canvasElement.width,
        canvasElement.height
      );

      var code = jsQR(imageData.data, imageData.width, imageData.height, {
        inversionAttempts: "dontInvert",
      });

      if (code) {
        outputMessage.hidden = true;
        outputData.parentElement.hidden = false;
        outputData.innerText = code.data;

        url.parentElement.hidden = false;
        url.setAttribute('href', 'http://localhost:3000/staff/buy_detail/' + code.data);
        sleep(5000);
      } else {
        outputMessage.hidden = false;
        outputData.parentElement.hidden = true;
        url.parentElement.hidden = true;
      }
    }
    requestAnimationFrame(tick);
  }
</script>

app/views/staff_pages/signin.html.erb
<h1>受付スタッフ</h1>

<h2>サインイン</h2>

<select name="test" size="3" multiple="multiple">
  <option value="test1" selected="selected">Aさん</option>
  <option value="test2">Aさん</option>
  <option value="test3">Aさん</option>
</select>

<%= link_to 'サインイン', staff_path, class: 'btn btn-primary' %>

app/views/ticket_shops/buy_ticket.html.erb
<h1>チケット購入 確認画面</h1>

<h2>イベント場所</h2>
<p><%= @event.event_place.name %></p>

<h2>日時</h2>
<p><%= @event.entry_time.to_date %></p>

<h2>イベント</h2>
<p><%= @event.event_name.name %></p>

<h2>時間</h2>
<img src="https://placehold.jp/150x150.png" class="img-fluid" alt="モックアップ">
<% str_time = [@event.entry_time.strftime("%R"),
                "~",
                @event.exit_time.strftime("%R")].join %>
<p><%= str_time %></p>

<h2>購入枚数</h2>

<div>
  <% @tickets.each do |ticket| %>
  <div>
    <p><%= ticket.name + ticket.price.to_s + '円' %></p>

    <p><%= '備考:' + ticket.detail %></p>
    <p>2枚</p>
  </div>
  <% end %>

  <p>合計金額 2,500円</p>
</div>

<%= link_to '購入', thanks_path, class: 'btn btn-primary' %>
<%= link_to '最初から選ぶ', root_path, class: 'btn btn-primary' %>

app/views/ticket_shops/select_date.html.erb
<h1>チケット購入</h1>

<h2>イベント場所</h2>
<p>○○シアター</p>

<h2>日時選択</h2>
<ul>
  <% @event_dates.each do |event_date| %>
   <li><%= link_to event_date, select_time_path %></li>
  <% end %>
</ul>

app/views/ticket_shops/select_place.html.erb
<h1>チケット購入</h1>

<h2>イベント会場選択</h2>
<ul>
  <% @event_places.each do |event_place| %>
    <li><%= link_to event_place.name , select_date_path %></li>
    <p><%= "最大収容人数：#{event_place.max_entry}名" %></p>
    <p><%= event_place.note %></p>
  <% end %>
</ul>

app/views/ticket_shops/select_ticket.html.erb
<h1>チケット販売</h1>

<h2>イベント場所</h2>
<p><%= @event.event_place.name %></p>

<h2>日時</h2>
<p><%= @event.entry_time.to_date %></p>

<h2>イベント</h2>
<p><%= @event.event_name.name %></p>

<h2>時間</h2>
<img src="https://placehold.jp/150x150.png" class="img-fluid" alt="モックアップ">
<% str_time = [@event.entry_time.strftime("%R"),
                "~",
                @event.exit_time.strftime("%R")].join %>
<p><%= str_time %></p>

<h2>購入枚数</h2>

<div>
  <% @tickets.each do |ticket| %>
  <div>
    <p><%= ticket.name + ticket.price.to_s + '円' %></p>

    <p><%= '備考:' + ticket.detail %></p>
    <select name="count">
      <option value="0" selected="selected">0</option>
      <% ticket.event_time.max_entry.times do |i| %>
        <option value="<%= i + 1 %>"><%= i + 1 %></option>
      <% end %>
    </select>
  </div>
  <% end %>
</div>

<%= link_to '次へ', buy_ticket_path, class: 'btn btn-primary' %>

app/views/ticket_shops/select_time.html.erb
<h1>チケット販売</h1>

<h2>イベント場所</h2>
<p><%= @event_names.first.first.event_place.name %></p>

<h2>日時</h2>
<p><%= @event_names.first.first.entry_time.to_date %></p>

<h2>イベント選択</h2>

<% @event_names.each do |event_name|%>
  <div class="row">
  <h3><%= event_name.first.event_name.name %></h3>

  <div class="col-md-4">
    <img src="https://placehold.jp/150x150.png" class="img-fluid" alt="モックアップ">
  </div>

  <div class="col-md-8">
    <% event_name.each do |event| %>
      <% str_time = [event.entry_time.strftime("%R"),
                    "~",
                    event.exit_time.strftime("%R")].join %>
      <li><%= link_to str_time, select_ticket_path %> </li>
    <% end %>
    </div>
  </div>
<% end %>

app/views/ticket_shops/thanks.html.erb
<h1>ご購入ありがとうございます。</h1>

<%= link_to 'マイページ', mypage_path, class: 'btn btn-primary' %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :tel, style: "display: block" %>
    <%= form.text_field :tel %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Tel:</strong>
    <%= user.tel %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user.password %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/mypage.html.erb
<h1>マイページ</h1>

<%= link_to '購入履歴', order_history_path, class: 'btn btn-primary' %>
<%= link_to '会員情報', '/users/1', class: 'btn btn-primary' %>
<%= link_to 'ログアウト', '#', class: 'btn btn-primary' %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/order_detail.html.erb
<h1>チケット販売</h1>

<div>
  <%= @svg %>
</div>

<h2>イベント場所</h2>
<% event_time = @sale.tickets.first.event_time %>
<p><%= event_time.event_place.name %></p>

<h2>日時</h2>
<p><%= event_time.entry_time.to_date %></p>

<h2>イベント</h2>
<p><%= event_time.event_name.name %></p>

<h2>時間</h2>
<img src="https://placehold.jp/150x150.png" class="img-fluid" alt="モックアップ">
<% str_time = [event_time.entry_time.strftime("%R"),
            "~",
            event_time.exit_time.strftime("%R")].join %>
<p><%= str_time %></p>

<h2>購入枚数</h2>
<% @sale.tickets.each do |ticket| %>
  <% sale_ticket = SaleTicket.find_by(sale_id: @sale.id, ticket_id: ticket.id) %>
  <% @total_price += ticket.price * sale_ticket.count %>
  <p><%= "#{ticket.name} #{ticket.price}円 #{sale_ticket.count}枚" %></p>
  <p><%= "備考: #{ticket.detail}"%></p>
<% end %>

<p><%= "合計金額 #{@total_price}円" %></p>

<%= link_to '購入履歴', order_history_path, class: 'btn btn-primary' %>

app/views/users/order_history.html.erb
<h1>購入履歴</h1>

<% @sales.each do |sale| %>
  <div style="border: solid medium">
    <h2>イベント場所</h2>
    <% event_time = sale.tickets.first.event_time %>
    <p><%= event_time.event_place.name %></p>

    <h2>日時</h2>
    <p><%= event_time.entry_time.to_date %></p>

    <h2>イベント</h2>
    <p><%= event_time.event_name.name %></p>

    <h2>時間</h2>
    <img src="https://placehold.jp/150x150.png" class="img-fluid" alt="モックアップ">
    <% str_time = [event_time.entry_time.strftime("%R"),
                "~",
                event_time.exit_time.strftime("%R")].join %>
    <p><%= str_time %></p>

    <h2>購入枚数</h2>
    <% sale.tickets.each do |ticket| %>
      <% sale_ticket = SaleTicket.find_by(sale_id: sale.id, ticket_id: ticket.id) %>
      <p><%= ticket.name + "#{sale_ticket.count}" + "枚" %></p>
    <% end %>
    
    <%= link_to 'チケット情報', order_detail_path, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>

app/views/users/signin.html.erb
<h1>サインアップ</h1>

<form method="POST" action="sample.cgi">
	<p>メールアドレス<input type="text" name="NAME"></p>
	<p>パスワード<input type="text" name="email"></p>
	<p><input type="submit" value="サインイン"></p>
	<p><input type="submit" value="新規登録"></p>
</form>

<%= link_to 'マイページ', thanks_path, class: 'btn btn-primary' %>

app/views/users/signup.html.erb
<h1>サインアップ</h1>

<form method="POST" action="sample.cgi">
	<p>メールアドレス<input type="text" name="NAME"></p>
	<p>パスワード<input type="text" name="email"></p>
	<p><input type="submit" value="新規登録"></p>
</form>